# DESCRIPTION
# this module downloads SRA files and converts them to FASTQ format.
# the output is a pair of FASTQ files for each SRA identifier.
#
# USAGE:
# alternative 1 -single target execution
# `mk <specific_target>` where specific_target is any line printed by `bin/mk-targets`
#
# alternative 2 -multiple target execution in tandem
# `bin/mk-targets | xargs mk`
#
#
# load options from file
#------------------------------
< config.mk
#
# download SRA files from NCBI
#------------------------------
'output/%.sra':
	mkdir -p `dirname $target`
	prefetch \
		--verbose
		--max-size $MAX_SIZE_FILES \
		--ascp-path $ASCP_PATH_AND_KEY \
		--output-directory `dirname $target` \
		`basename $stem`

