# DESCRIPTION
# this module downloads SRA files and converts them to FASTQ format.
# the output is a pair of FASTQ files for each SRA identifier.
#
# USAGE:
# alternative 1 -single target execution
# `mk <specific_target>` where specific_target is any line printed by `bin/targets`
#
# alternative 2 -multiple target execution in tandem
# `bin/targets | xargs mk`
#
#
# Load options from file
< config.mk
#
# dump SRA files into FASTQ format
#------------------------------
output/%_1.fastq.gz \
output/%_2.fastq.gz:	output/%.sra
	fastq-dump \
		--split-files \
		--gzip \
		--outdir `dirname $prereq`
		$prereq

# download SRA files from NCBI
#------------------------------


prefetch --verbose --max-size 300G --ascp-path "/home/hreyes/.aspera/connect/bin/ascp|/home/hreyes/.aspera/connect/etc/asperaweb_id_dsa.openssh" --output-directory output/ SRR1016425

'output([A-z0-9_/\-]*/)([A-z0-9]+)_[1|2].fastq.gz':R:
	mkdir -p `dirname $target`
	fastq-dump \
		--split-files \
		--gzip \
		--outdir `dirname $target` \
		$stem2
