# DESCRIPTION
# this module dumps SRA files downloaded with `01-prefetch` to FASTQ format.
# the output is a pair of FASTQ files for each SRA identifier.
#
# USAGE:
# alternative 1 -single target execution
# `mk <specific_target>` where specific_target is any line printed by `bin/mk-targets`
#
# alternative 2 -multiple target execution in tandem
# `bin/mk-targets | xargs mk`
#
# Read in config
< config.mk

# dump SRA files into FASTQ format
#------------------------------
output/%.fastq:	input/%.sra
	mkdir -p `dirname $target`
	fasterq-dump \
		--threads $FQD_THREADS \
		--progress \
		--split-files \
		--temp `dirname $target` \
		--outdir `dirname $target` \
		--outfile $stem \
		$prereq

