# DESCRIPTION
# this module dumps SRA files downloaded with `01-prefetch` to FASTQ format.
# the output is a pair of FASTQ files for each SRA identifier.
#
# USAGE:
# alternative 1 -single target execution
# `mk <specific_target>` where specific_target is any line printed by `bin/targets`
#
# alternative 2 -multiple target execution in tandem
# `bin/targets | xargs mk`
#
#
# Load options from file
< config.mk
#
# dump SRA files into FASTQ format
#------------------------------
output/%_1.fastq.gz \
output/%_2.fastq.gz:	output/%.sra
	fastq-dump \
		--split-files \
		--gzip \
		--outdir `dirname $prereq`
		$prereq

