# DESCRIPTION
# this module dumps SRA files downloaded with `01-prefetch` to FASTQ format.
# the output is a pair of FASTQ files for each SRA identifier.
#
# USAGE:
# alternative 1 -single target execution
# `mk <specific_target>` where specific_target is any line printed by `bin/mk-targets`
#
# alternative 2 -multiple target execution in tandem
# `bin/mk-targets | xargs mk`
#
#
# dump SRA files into FASTQ format
#------------------------------
output/%_1.fastq.gz:	input/%.sra
	mkdir -p `dirname $target`
	fastq-dump \
		--split-files \
		--readids \
		--gzip \
		--outdir `dirname $target` \
		$prereq

